### ISSUE TITLE
Python state files incompatible with ParaView 5.8

### ISSUE THREAD

**Issue by pierre-guillou** [topology-tool-kit/ttk-data#64]
While testing the ttk-data states with my ParaView 5.8.1, the following error occurred with `nestedTrackingFromOverlap.py`:

> AttributeError: type object 'RenderView' has no attribute 'EnvironmentNorth'

Apart from `nestedTrackingFromOverlap.py`, the `EnvironmentNorth` attribute is also present in `trackingFromOverlap.py` which fails in the same manner. Both of these files were introduced in #62.

No error occurred when testing with ParaView 5.9.
Should the states be only compatible with the last ParaView version?

Pierre

**Comment by JonasLukasczyk** [comment]
Hi @pierre-guillou, good find. Seems like PV5.9 added some attributes 5.8 does not know about. I did not explicitly set `EnvironmentNorth` so can you try to just delete this stuff from the python file and check if it is still working correctly?

**Comment by pierre-guillou** [comment]
Hi Jonas,
Thanks for your suggestion. However, I switched to ParaView 5.9 on all my computers since. I will try with an older ParaView version when I get time (to see if other attributes cause errors).
